name: LOC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - run: wc -l app.js > /tmp/loc.txt
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
        host: smtp.google.com
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: xopacek110@colimarl.com # temp mail adres
        subject: mail title.
        body: your messages.
        attachments: '[{"path":"/tmp/loc.txt"}]'
